site_name: RNA Framework
pages:
    - 'Overview': 'index.md'
    - 'Framework components': 'components.md'
    - 'rf-index': 'rf-index.md'
    - 'rf-count': 'rf-count.md'
    - '': 'rf-norm.md'
    - 'rf-fold': 'rf-fold.md'
    - 'rf-compare': 'rf-compare.md'
    - 'rf-silico': 'rf-silico.md'
    - 'rf-modcall': 'rf-modcall.md'
    - 'rf-peakcall': 'rf-peakcall.md'
    - 'rf-combine': 'rf-combine.md'
    - 'Application cases': 'cases.md'
markdown_extensions:
    - markdown.extensions.admonition